apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerconfigjson-github-com
  namespace: practice-space
  labels:
    app: ghcr
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZbWhoZG1scllUYzVPbWRvY0Y5MlMzQmFXVFpqZW1aMGNtbE1UV3BGUzB4R1dVbFVSemhRUkZWd2NIUTBZM2xPYmpJPSJ9fX0=
