apiVersion: v1
kind: Service
metadata:
  name: travel-service
  namespace: practice-space
spec:
  selector:
    app: travel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
